notifications:
  recipients:
    - koji.shimada@enishi-tech.com
language: ruby
rvm:
  - 2.1.0
  - 2.1.2
before_install:
  - gem install bundler
  - curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh
